# Generated by Django 6.0.5 on 2026-05-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('contenido', models.TextField()),
                ('imagen', models.CharField(blank=True, max_length=300)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_original', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('imagen', models.CharField(max_length=300)),
                ('fecha_lanzamiento', models.DateField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('destacado', models.BooleanField(default=False)),
                ('top_ventas', models.BooleanField(default=False)),
                ('novedad', models.BooleanField(default=False)),
                ('en_descuento', models.BooleanField(default=False)),
                ('genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos', to='juegos.genero')),
                ('plataforma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos', to='juegos.plataforma')),
            ],
        ),
    ]
